"""update user

Revision ID: c01ec1e9147d
Revises: 80cb5233a81e
Create Date: 2023-12-08 16:08:50.765163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01ec1e9147d'
down_revision = '80cb5233a81e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middlename', sa.String(length=32), nullable=True))
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.drop_column('middlename')

    # ### end Alembic commands ###
