"""empty message

Revision ID: ec5008dcb7a2
Revises: c01ec1e9147d
Create Date: 2023-12-11 13:19:36.120385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5008dcb7a2'
down_revision = 'c01ec1e9147d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_register',
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pre_register')
    # ### end Alembic commands ###
