"""Extended pre-register

Revision ID: fe9177f210a0
Revises: ec5008dcb7a2
Create Date: 2023-12-12 11:21:37.315618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9177f210a0'
down_revision = 'ec5008dcb7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_register', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
